dist: xenial

language: python

cache: pip # Cache allows for python package versions to be stored between runs, to speed up sequential builds. 

python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
 
matrix:
    allow_failures:
        - python: "nightly" 
        - python: "3.8-dev"
 
install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pipenv install --dev